# Generated by Django 5.2.11 on 2026-03-17 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=20, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Nobreak', 'Nobreak'), ('Smartphone', 'Smartphone'), ('Servidor', 'Servidor'), ('Impressora', 'Impressora'), ('Switch', 'Switch'), ('Outro', 'Outro')], max_length=30)),
                ('estado', models.CharField(choices=[('em_uso', 'Em Uso'), ('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('descartado', 'Descartado')], default='estoque', max_length=20)),
                ('custodiante', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['patrimonio'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('unidade', models.CharField(default='pc', max_length=20)),
                ('nivel_minimo', models.PositiveIntegerField(default=0)),
                ('qtde', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('origem', models.CharField(choices=[('Infra', 'Infra'), ('Suporte', 'Suporte'), ('ERP', 'ERP'), ('Sistemas Internos', 'Sistemas Internos'), ('BI', 'BI'), ('Compras', 'Compras'), ('Manutenção', 'Manutenção')], max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('média', 'Média'), ('alta', 'Alta')], default='média', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('sla_horas', models.PositiveIntegerField(default=8)),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='core.ativo')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-aberto_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.chamado')),
            ],
            options={
                'verbose_name': 'Histórico de Chamado',
                'verbose_name_plural': 'Históricos de Chamados',
                'ordering': ['quando'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Site', 'Site'), ('Prédio', 'Prédio'), ('Andar', 'Andar'), ('Sala', 'Sala'), ('Rack', 'Rack')], max_length=30)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='core.local')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='ativo',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='core.local'),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20)),
                ('area', models.CharField(choices=[('Infraestrutura de T.I', 'Infraestrutura de T.I'), ('Administrativo', 'Administrativo'), ('Comercial', 'Comercial'), ('Controle Industrial', 'Controle Industrial')], max_length=50)),
                ('percentual', models.FloatField(default=0.0)),
                ('prazo', models.DateField()),
                ('atrasado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['prazo'],
            },
        ),
    ]
