# Generated by Django 5.2.11 on 2026-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=60, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#94a3b8', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coluna Kanban',
                'verbose_name_plural': 'Colunas Kanban',
                'ordering': ['ordem'],
            },
        ),
    ]
