# Generated by Django 5.2.11 on 2026-04-22 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kanbancoluna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='custodiante',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='categoria',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop'), ('Monitor', 'Monitor'), ('Nobreak', 'Nobreak'), ('Smartphone', 'Smartphone'), ('Servidor', 'Servidor'), ('Impressora', 'Impressora'), ('Switch', 'Switch'), ('Outro', 'Outro')], max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='estado',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('descartado', 'Descartado')], default='estoque', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='core.local', verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='patrimonio',
            field=models.CharField(max_length=20, unique=True, verbose_name='Patrimônio'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='aberto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='assunto',
            field=models.CharField(max_length=120, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='core.ativo', verbose_name='Ativo relacionado'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='origem',
            field=models.CharField(choices=[('Infra', 'Infra'), ('Suporte', 'Suporte'), ('ERP', 'ERP'), ('Sistemas Internos', 'Sistemas Internos'), ('BI', 'BI'), ('Compras', 'Compras'), ('Manutenção', 'Manutenção')], max_length=30, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('média', 'Média'), ('alta', 'Alta')], default='média', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='sla_horas',
            field=models.PositiveIntegerField(default=8, verbose_name='SLA (horas)'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicochamado',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='historicochamado',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nivel_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Nível mínimo'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='qtde',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='unidade',
            field=models.CharField(default='pc', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='area',
            field=models.CharField(choices=[('Infraestrutura de T.I', 'Infraestrutura de T.I'), ('Administrativo', 'Administrativo'), ('Comercial', 'Comercial'), ('Controle Industrial', 'Controle Industrial')], max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='atrasado',
            field=models.BooleanField(default=False, verbose_name='Atrasado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='percentual',
            field=models.FloatField(default=0.0, verbose_name='Percentual (%)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo',
            field=models.DateField(verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='nao_iniciado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('contato', models.CharField(blank=True, max_length=20, verbose_name='Contato')),
                ('ramal', models.CharField(blank=True, max_length=10, verbose_name='Ramal')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodiantes', to='core.ativo', verbose_name='Patrimônio atribuído')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
