# Generated by Django 5.2.11 on 2026-04-29 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_criar_funcionario_remover_custodiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicochamado',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicochamado',
            name='tipo',
            field=models.CharField(blank=True, choices=[('status', 'Alteração de Status'), ('prioridade', 'Alteração de Prioridade'), ('atribuicao', 'Atribuição'), ('comentario', 'Comentário')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicochamado',
            name='valor_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicochamado',
            name='valor_novo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicochamado',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.CreateModel(
            name='AnexoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chamados/anexos/%Y/%m/')),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.chamado')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['quando'],
            },
        ),
    ]
