# Generated by Django 6.0.2 on 2026-05-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chamado_atualizado_em_historicochamado_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('percentual', models.FloatField(default=0.0, verbose_name='Progresso (%)')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('cor', models.CharField(default='gray', max_length=20, verbose_name='Cor')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coluna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.kanbancoluna')),
            ],
            options={
                'verbose_name': 'Card Kanban',
                'verbose_name_plural': 'Cards Kanban',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
