# Generated by Django 5.0.6 on 2026-05-05 23:43

import apps.core.models.chamado
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_locais_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexochamado',
            name='arquivo',
            field=models.FileField(upload_to='chamados/anexos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'txt']), apps.core.models.chamado.validar_tamanho_anexo]),
        ),
    ]
