# Generated by Django 5.0.6 on 2026-05-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kanban_audit_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
