# Generated by Django 5.0.6 on 2026-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remover_modelo_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='patrimonio',
            new_name='ativo_atribuido',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
    ]
