# Generated by Django 6.0.2 on 2026-06-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_departamentos_topicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='sku',
        ),
    ]
